library(dplyr)
library(plotly)
library(stringr)
library(rgdal)
library(tidyverse)
library(ggmap)
library(DT)
library(knitr)
library(leaflet)
library(tigris)
library(geojsonio)

rents_df <- read.csv("Metro_MedianRentalPrice_2Bedroom.csv", stringsAsFactors = FALSE)

rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2010.", "2010/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2011.", "2011/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2012.", "2012/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2013.", "2013/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2014.", "2014/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2015.", "2015/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2016.", "2016/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2017.", "2017/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2018.", "2018/")))
rents_df <- rename_if(rents_df, is.numeric, funs(str_replace(., "X2019.", "2019/")))